const state = [
    "Maharashtra",      
    "Karnataka",         
    "West Bengal",       
    "Tamil Nadu",        
    "Telangana",         
    "Gujarat",           
    "Rajasthan",         
    "Uttar Pradesh",    
    "Madhya Pradesh",    
    "Andhra Pradesh",    
    "Maharashtra",       
    "Bihar",             
    "Haryana",           
    "Punjab",            
    "Uttarakhand",       
    "Jharkhand",         
    "Odisha",            
    "Chhattisgarh",      
    "Assam",             
    "Jammu & Kashmir",   
    "Delhi",             
    "Chandigarh",        
    "Himachal Pradesh",  
    "Goa",               
    "Kerala",            
    "Manipur",           
    "Mizoram",          
    "Tripura",           
    "Sikkim",            
    "Arunachal Pradesh", 
    "Nagaland",          
    "Meghalaya",         
    "Puducherry",       
    "Andaman & Nicobar Islands" 
  ];
  
  export default state;
  